services:
  # Configuré el contenedor de la base de datos con SQL Server 2022  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordFuerte123! # Definí una contraseña segura para el usuario SA
    networks:
      - app-network

  # Configuré el contenedor de mi API vinculándolo con el servicio de base de datos
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prueba_tecnica_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=PruebaTecnicaDb;User Id=sa;Password=TuPasswordFuerte123!;TrustServerCertificate=True
    depends_on:
      - db # Aseguré que la base de datos inicie antes que la API
    networks:
      - app-network

networks:
  app-network:
    driver: bridge